name: Build Docker Image

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Python script to output JSON matrix
        id: set-matrix
        run: |
          python3 generate-builds.py > matrix.json
          matrix=$(jq -c '.' matrix.json)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build-image:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    if: needs.generate-matrix.outputs.matrix != '[]'
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            SATDUMP_VERSION=${{ matrix.data.version }}
            SATDUMP_RELEASE_FILE_AMD64=${{ matrix.data.release_file_amd }}
            SATDUMP_RELEASE_FILE_ARM64=${{ matrix.data.release_file_arm }}
          tags: ${{ join(matrix.data.tags, ',') }}
